baseURL = "https://zjpsycholin.github.io/SLA4ug/"
languageCode = "en-us"
title = "Second Language Acquisition (Undergraduate)"
theme = "archie"
copyright = "© Zhang Jun"





[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[params]
  mode = "auto"
  useCDN = false
  subtitle = ""
  katex = true

[menu]
  [[menu.main]]
    name = "Welcome"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 2

  [[menu.main]]
    name = "Chapter 1"
    url = "/chapter1/"
    weight = 3

  [[menu.main]]
    name = "Chapter 2"
    url = "/chapter2/"
    weight = 4

  [[menu.main]]
    name = "Chapter 3"
    url = "/chapter3/"
    weight = 5

  [[menu.main]]
    name = "Chapter 4"
    url = "/chapter4/"
    weight = 6

  [[menu.main]]
    name = "Chapter 5"
    url = "/chapter5/"
    weight = 7

  [[menu.main]]
    name = "Chapter 6"
    url = "/chapter6/"
    weight = 8

  
